### PR TITLE
2.process data split

### PR DESCRIPTION
**Pull request by wagenrace**
The following pull request adds, fixes, and/or modifies:

Add 2.process_data with the function of splitting the data into training and testing. Process is added to the pipeline

I performed the following prior to filing this pull request:

- [X] Tested that my change does not break the analysis pipeline
- [X] Ran a linter through my code
- [X] Update environment dependencies if my code introduces a new package

### CODE REVIEW

**Comment by gwaygenomics** [comment]
A bit confused why this is a PR. Is this just a copy of #12? Except it looks like 4878294f6e7167bb9f454fabddd9730856c2ada3 is new.

Instead of opening a new fork, can you just add that commit to my fork?

Alternatively, I can add 4878294f6e7167bb9f454fabddd9730856c2ada3 and rebase to make you an author of this commit.

It is extremely important that all code contributions are documented on github as they were originally authored.

**Comment by gwaygenomics** [comment]
> Instead of opening a new fork, can you just add that commit to my fork?

@wagenrace - I just gave you [`maintain`](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) access to this repo, so you should now be able to commit directly to my fork

I won't be able to complete #12 until tomorrow. If you don't have time to commit 4878294f6e7167bb9f454fabddd9730856c2ada3 to my branch directly, I will add it to my branch, rebase, and make you an author of that commit. Then, we can close this PR and merge in #12

**Comment by wagenrace** [comment]
Sorry, bit late reaction. I made this a separate PR to make sure every PR has one function. I saw you where already busy with the next steps after separating the data

**Comment by gwaygenomics** [comment]
No worries, the productivity is great. I am working on consolidating this PR with #12 and will tag you soon to review

**Pull request closed without merging**
