### PR TITLE
Project Goals and Specify No Black on Autogenerated Files

### LINKED ISSUE #29: Update CONTRIBUTING.md to specify no black for autogenerated files
python scripts generated by a `jupter nbconvert --to-script` command should not be autoformatted with `black`. These are autogenerated files that should only show changes with the associated `.ipynb` file is updated.

### PR DESCRIPTION
**Pull request by gwaygenomics**
The following pull request adds, fixes, and/or modifies:

* [M] `CONTRIBUTING.md`
  * Adds instructions to avoid applying `black` to autogenerated files. (closes #29 )
  * Adds Jupyter notebook section specifying to `nbconvert` `.ipynb` files prior to merging
  * Adds project goals section specifying our mission statement and scientific goals
* [M] `PULL_REQUEST_TEMPLATE.md`
  * Adds link to contributing file in pull request template.

I performed the following prior to filing this pull request:

- [x] Tested that my change does not break the analysis pipeline
- [x] Ran a linter through my code
- [x] Update environment dependencies if my code introduces a new package

### CODE REVIEW

**Comment by gwaygenomics** [comment]
cc @pearsy - it would be great to get your feedback on this too

**Comment by gwaygenomics** [comment]
I plan on merging this on Friday (Jan 3)

**Comment by pearsy** [comment]
ok sure, will do this week.

**Comment by gwaygenomics** [comment]
thanks @pearsy - I just merged this in 2 minutes before your comment, so please fee free to open a new issue or PR to incorporate any changes you might have

**Comment by pearsy** [comment]
noted!

**Pull request merged**
