### PR TITLE
add windows instruction

### PR DESCRIPTION
**Pull request by wagenrace**
Add instruction for windows users. It is the way I got it working on my own machine but have not tested if it is clear to somebody else

### CODE REVIEW

**Comment by gwaygenomics** [comment]
This is great @wagenrace - thanks for adding.

Here are some of my thoughts:

- I think this material is better suited as a [wiki page](https://github.com/cytodata/single-cell-classifier/wiki)
- Once added as a wiki page, we can link directly to the wiki page in the readme.

So the readme will have an [H3 Heading](https://www.markdownguide.org/basic-syntax/) in the `Computation Environment` section (H2 heading) that says something along the lines of 

```
### Windows Install

To install the appropriate computational environment for a windows machine, review the instructions here (and add link to wiki)
```

The idea is to reduce clutter in the README, which is the most important page for new users wishing to get oriented to the project. If I were viewing a project for the first time, I'd want only absolutely essential information in the README. 1) What is the project name; 2) what does the project aim to solve; 3) what are the key results; 4) instructions on how to reproduce analysis

**Comment by gwaygenomics** [comment]
For this point: "4) instructions on how to reproduce analysis"

Instructions on how to reproduce the computational environment in windows is a huge bonus

**Comment by wagenrace** [comment]
I full agree with some kind of structured documentation (like a wiki). Can I make it here or do I need to be a contributor to the project?

**Comment by gwaygenomics** [comment]
I just sent over permissions - you should be good to add the wiki documentation here now

**Comment by wagenrace** [comment]
Great, it works. I will make a start with the wiki

**Pull request closed without merging**
